# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Card": "00_card.ipynb"}

modules = ["card.py"]

doc_url = "https://VSJ1996.github.io/nwu_cards_demo/"

git_url = "https://github.com/VSJ1996/nwu_cards_demo/tree/{branch}/"

def custom_doc_links(name): return None
